### PR TITLE
e1: highlight outdated extension versions (fix logic)

### PR DESCRIPTION
**Pull request by NikolayS**
It is incorrect to compare `pg_available_extensions.installed_version` to `pg_extension.extversion`, it should be compared to `pg_available_extensions.default_version`. It led to incorrectly working `actuality` flag – at all times it was empty.

This commit fixes it. Also, `available_extension` column is removed – its logic was wrong from the very beginning.

Example:
- before fix:
```
        name        | installed_version | default_version | available_version | actuality
--------------------+-------------------+-----------------+-------------------+-----------
 pg_stat_statements | 1.2               | 1.4             | 1.2               |
 plpgsql            | 1.0               | 1.0             | 1.0               |
(2 rows)
```

- after fix:
```
        name        | installed_version | default_version | actuality
--------------------+-------------------+-----------------+-----------
 pg_stat_statements | 1.2               | 1.4             | OLD
 plpgsql            | 1.0               | 1.0             |
(2 rows)
```

### CODE REVIEW

**Comment by Nastradamus** [comment]
Neat.
Do we need to fill `actuality` with something if everything is ok? E.g., following example looks slightly empty:
```
  name   | installed_version | default_version | actuality
---------+-------------------+-----------------+-----------
 plpgsql | 1.0               | 1.0             |
 plsh    | 2                 | 2               |
(2 rows)

```

**Comment by NikolayS** [comment]
@Nastradamus I've renamed the column to `is_old`

**Comment by Nastradamus** [comment]
@NikolayS should we use `true` or `false` as a required value for this column (`id_old`)?

**Comment by NikolayS** [comment]
@Nastradamus here we come to the question, what is better for humans and what is better for "robots".
The current way how it's implemented -- it's better for humans. If "it is not old", we don't see anything in the column (if NULLs representation is not tuned in psql), and easily catch "OLD" rows.

For robots, it would be more appropriate to have true/false, yes.

**Pull request merged**
